### ISSUE TITLE
Vlastní velikost avataru: Parametrizace požadavku na obrázek

### ISSUE THREAD

**Issue by janbarasek** [baraja-core/gravatar#3]
Velmi často potřebuje vývojář ikonku ve specifické velikosti, proto by bylo dobré přímo při požadavku na obrázek umožnit zadat vlastní velikost v pixelech.

Použití pak bude například:

```php
$gravatar = new Gravatar;

// default icon size
echo $gravatar->getIcon('jan@barasek.com');

// small icon size
echo $gravatar->getIcon('jan@barasek.com', 32);

// big icon size
echo $gravatar->getIcon('jan@barasek.com', 255);
```

Velikost obrázku se konfiguruje parametrem `?s=`. Více info v dokumentaci: https://en.gravatar.com/site/implement/images/

Parametr musí být nepovinný (když nezadá nic, předpokládej `null`). Přijímej jen int a null. Pokud zadá rozměr, validuj, že je v intervalu `<1, 5000>`, jinak `InvalidArgumentException`.

Popis tohoto chování napiš také do souboru README.md, překopíruj ukázku z tohoto zadání.

Díky.

**Comment by filipjakub** [comment]
Hotovo

@janbarasek

**Comment by janbarasek** [comment]
@filipjakub Rád bych viděl řešení přes funkci `http_build_query()`, která zjednodušuje syntaxi a proces skládání URL.
