### ISSUE TITLE
Konstruktor: Nastavení výchozí chybové ikonky a cachování dotazů

### ISSUE THREAD

**Issue by janbarasek** [baraja-core/gravatar#4]
V rámci tohoto úkolu je potřeba do služby `Gravatar` implementovat konstruktor, který bude mít 2 nepovinné parametry:

```php
class Gravatar
{
   public function __construct(?string $defaultIcon = null, ?string $cacheDir = null)
   {
      // implement me!
   }
}
```

První parametr umožňuje nastavit výchozí ikonku, pokud uživatelská ikonka neexistuje. Toto nastavení chci mít v konstruktoru, aby bylo chování společné pro všechna volání. Info o výchozí ikonce je zde: https://en.gravatar.com/site/implement/images/

Na vstupu validuj, že vývojář zadal validní typ výchozí ikonky nebo URL (`Validators::isUrl()`).

Cache síťových požadavků
------

Požadavky na meta data zdržují síťový provoz a mohou být v čase omezené. Zkus implementovat drobnou souborovou cache, která bude požadavek na konkrétní meta data ukládat po dobu 60 minut.

Diskovou cestu pro cache adresář může vývojář buď zadat, nebo ji vygeneruj automaticky. To jde udělat třeba takto:

```php
$cacheDir = $cacheDir ?? sys_get_temp_dir() . '/gravatar/' . md5(__DIR__);
```

Pokud disková cesta neexistuje, vytvoř ji: `FileSystem::createDir($cacheDir);`.

Cache požadavků je dobré ověřovat těsně před zavoláním URL. Jako cachovací klíč použij hash URL adresy. Při čtení cache ověřuj, že už není zastaralá, pokud ano, pokládej ji za neplatnou a data stáhni znovu. Po stažení dat je potřeba zapsat do cache.

Do cache zapisuj jen požadavky z metody `getUserInfo()` a ukládej jen response z HTTP komunikace. Instanci entity `GravatarResponse` a sestavení dat prováděj vždy.

Cache lze implementovat mnoha způsoby. Zajímá mě, co si vybereš ty. :)

**Comment by filipjakub** [comment]
Cache bych měl nejspíš hotovou.

Co se týče té defaultní ikonky, stačí to jen encodnout a připojit na konec toho returnu v `getIcon` nebo to mám vyřešit nějak lépe?

@janbarasek

**Comment by janbarasek** [comment]
@filipjakub Díky, takto to stačí.

Samozřejmě musíš vždy všechny vstupy korektně escapovat, aby nemohlo dojít k bezpečnostní zranitelnosti.
